### ISSUE TITLE
Update README to mention Macchina support?

### ISSUE THREAD

**Issue by adamvoss** [atlas0fd00m/CanCat#18]
Currently the README indicates Macchina could potentially be supported in the future, but commit history suggests support for the M2 has been introduced.  Could the README be updated?

/ref https://github.com/macchina/showcase/pull/5

**Comment by atlas0fd00m** [comment]
certainly.  thanks for pointing this out.

**Comment by mi-hol** [comment]
@adamvoss  @atlas0fd00m as Macchina is mentioned. Could this be closed?

**Comment by straithe** [comment]
I believe this is done now, and this issue can be closed.
