### ISSUE TITLE
Clarification on Python Version

### ISSUE THREAD

**Issue by decidedlygray** [atlas0fd00m/CanCat#50]
Hello,

While trying to debug an issue I'm having with getting CanCat up and running I noticed this:
```
#!/usr/bin/env python3
```
From: https://github.com/atlas0fd00m/CanCat/blob/master/CanCat.py#L1

The main README still says Python 2.7. I haven't pulled the latest in about a month, but when I do should I be using Python3?

**Comment by atlas0fd00m** [comment]
yes, we had to leave py2 behind.  we need to update the README, sorry!
py2 requirement was making it increasingly difficult to use CanCat.
