### ISSUE TITLE
Prebuilded FW images cause Arduino builds fail 

### ISSUE THREAD

**Issue by iDoka** [atlas0fd00m/CanCat#8]
My trying of builds after several hour is fail.
I suppose inappropriate tool version or unresolved depencies ($ avr-gcc -v is gcc version 4.9.2 (Fedora 4.9.2-1.el7))
Could you provide proper FW for Arduino UNO or maybe proven Makefile for build it my own? (GUI-based tools is really hard to understand build working)

![screenshot from 2016-10-30 22-52-18](https://cloud.githubusercontent.com/assets/4820969/19986529/8f45b0e2-a230-11e6-8010-ef05df21b236.png)
![screenshot from 2016-10-30 22-53-05](https://cloud.githubusercontent.com/assets/4820969/19986683/1c6b182c-a231-11e6-907b-dd6c4cd78d27.png)

Thanks in advance!

**Comment by atlas0fd00m** [comment]
closing due to age.  please reopen if you still have issues.  
most CanCats these days are running on Arduino DUE or Maccina M2 hardware, so the build uses different libraries.
